### ISSUE TITLE
minor mishap with colors in README

### ISSUE THREAD

**Issue by skaurus** [hygge-io/golor#1]
Your example uses `#(green,italic){combine}`, and then in the image showcasing the result that text is purple :)

**Comment by AntoineToussaint** [comment]
Oh thank you! I am also color blind but here it's just laziness ;)

**Comment by skaurus** [comment]
Oh, wow! So cool that you are working on the color-related library.

**Comment by AntoineToussaint** [comment]
I added convenience functions and will rename the package. I am working on a CLI and that's quite useful to have some nicer text. If I had a bit of time, defining styles instead of individual colors would be quite nice.

**Comment by AntoineToussaint** [comment]
@skaurus Let me know if the style feature is something you would want to help with by the way!
